"""
GitHub API router: connect accounts, list repos, push pipeline artifacts.
"""

from __future__ import annotations

import json
import logging
import secrets
from typing import Any, Optional
from urllib.parse import urlencode

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from pydantic import BaseModel
from supabase import Client

from backend.app.auth.dependencies import get_current_user
from backend.app.config import get_settings
from backend.app.github.service import GitHubService, get_github_service
from backend.app.supabase_client import get_supabase_dependency

logger = logging.getLogger(__name__)

router = APIRouter()
oauth_states: dict[str, dict[str, str]] = {}


class ConnectGitHubRequest(BaseModel):
    access_token: str


class GitHubOAuthStartResponse(BaseModel):
    authorization_url: str


class CreateRepoRequest(BaseModel):
    name: str
    description: str = ""
    private: bool = True


class PushCodeRequest(BaseModel):
    repo_full_name: str
    pipeline_id: str
    branch: Optional[str] = None
    commit_message: str = "feat: auto-generated by Multi-Agent Pipeline"
    create_pr: bool = False


class CreateBranchRequest(BaseModel):
    repo_full_name: str
    branch_name: str
    from_branch: Optional[str] = None


def _assert_pipeline_access(pipeline_id: str, user_id: str, supabase: Client) -> dict[str, Any]:
    """Ensure pipeline exists and belongs to the current user."""
    pipe = (
        supabase.table("pipelines")
        .select("id, project_id")
        .eq("id", pipeline_id)
        .maybe_single()
        .execute()
    )
    if not pipe.data:
        raise HTTPException(status_code=404, detail="Pipeline not found")

    project = (
        supabase.table("projects")
        .select("id")
        .eq("id", pipe.data["project_id"])
        .eq("owner_id", user_id)
        .maybe_single()
        .execute()
    )
    if not project.data:
        raise HTTPException(status_code=403, detail="Access denied")

    return pipe.data


def _extract_files(content: Any) -> dict[str, str]:
    """Extract pushable files from known artifact shapes."""
    if not isinstance(content, dict):
        return {}

    result: dict[str, str] = {}
    files = content.get("files")

    # Shape 1: {"files": {"path": "content"}}
    if isinstance(files, dict):
        for file_path, file_content in files.items():
            if not file_path:
                continue
            if isinstance(file_content, str):
                result[str(file_path)] = file_content
            else:
                result[str(file_path)] = _to_json(file_content)

    # Shape 2: {"files": [{"path": "...", "content": "..."}]}
    if isinstance(files, list):
        for index, item in enumerate(files):
            if not isinstance(item, dict):
                continue
            file_path = str(item.get("path") or f"generated/file_{index}.txt")
            file_content = item.get("content", "")
            result[file_path] = file_content if isinstance(file_content, str) else _to_json(file_content)

    # Shape 3: deployment-style fields
    if isinstance(content.get("dockerfile"), str):
        result.setdefault("Dockerfile", content["dockerfile"])
    if isinstance(content.get("docker_compose"), str):
        result.setdefault("docker-compose.yml", content["docker_compose"])
    if isinstance(content.get("ci_cd_pipeline"), str):
        result.setdefault(".github/workflows/pipeline.yml", content["ci_cd_pipeline"])

    return result


@router.post("/connect")
async def connect_github(
    body: ConnectGitHubRequest,
    user: dict = Depends(get_current_user),
    supabase: Client = Depends(get_supabase_dependency),
):
    """Connect a GitHub account by storing access token."""
    try:
        gh = GitHubService(body.access_token)
        username = gh.username

        supabase.table("github_tokens").upsert({
            "user_id": user["id"],
            "access_token": body.access_token,
            "github_username": username,
        }).execute()

        return {
            "connected": True,
            "github_username": username,
        }
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid GitHub token: {exc}")


@router.get("/oauth/url", response_model=GitHubOAuthStartResponse)
async def github_oauth_url(
    redirect_path: str = Query("/dashboard/settings"),
    user: dict = Depends(get_current_user),
):
    """Return a GitHub OAuth authorization URL for the authenticated user."""
    settings = get_settings()
    if not settings.github_client_id or not settings.github_client_secret:
        raise HTTPException(status_code=500, detail="GitHub OAuth is not configured")

    state = f"github_oauth:{secrets.token_urlsafe(32)}"
    oauth_states[state] = {
        "user_id": user["id"],
        "redirect_path": redirect_path if redirect_path.startswith("/") else "/dashboard/settings",
    }
    return {"authorization_url": GitHubService.get_oauth_url(state)}


@router.get("/oauth/callback")
async def github_oauth_callback(
    code: str = Query(...),
    state: str = Query(...),
    supabase: Client = Depends(get_supabase_dependency),
):
    """Handle GitHub OAuth callback and persist the token for the initiating user."""
    settings = get_settings()
    session = oauth_states.pop(state, None)
    redirect_path = "/dashboard/settings"
    if session:
        redirect_path = session.get("redirect_path", redirect_path)

    target_base = f"{settings.frontend_url.rstrip('/')}{redirect_path}"

    def redirect_with(params: dict[str, str]) -> RedirectResponse:
        return RedirectResponse(f"{target_base}?{urlencode(params)}")

    if not session:
        return redirect_with({"github": "error", "message": "Invalid or expired OAuth state"})

    try:
        token_data = GitHubService.exchange_code(code)
        access_token = token_data.get("access_token")
        if not access_token:
            return redirect_with({"github": "error", "message": "Failed to obtain GitHub access token"})

        gh_user = GitHubService.get_user_info_from_token(access_token)
        username = gh_user.get("login")
        if not username:
            return redirect_with({"github": "error", "message": "Failed to fetch GitHub user"})

        supabase.table("github_tokens").upsert({
            "user_id": session["user_id"],
            "access_token": access_token,
            "github_username": username,
        }).execute()

        return redirect_with({"github": "connected", "username": username})
    except Exception as exc:
        logger.error("GitHub OAuth callback failed: %s", exc, exc_info=True)
        return redirect_with({"github": "error", "message": str(exc)})


@router.get("/status")
async def github_status(
    user: dict = Depends(get_current_user),
    supabase: Client = Depends(get_supabase_dependency),
):
    """Check if GitHub is connected."""
    try:
        result = (
            supabase.table("github_tokens")
            .select("github_username")
            .eq("user_id", user["id"])
            .maybe_single()
            .execute()
        )
        if result and result.data:
            return {
                "connected": True,
                "github_username": result.data["github_username"],
            }
    except Exception as exc:
        logger.error(f"Error checking GitHub status: {exc}")
    
    return {"connected": False}


@router.delete("/disconnect")
async def disconnect_github(
    user: dict = Depends(get_current_user),
    supabase: Client = Depends(get_supabase_dependency),
):
    """Disconnect GitHub account."""
    supabase.table("github_tokens").delete().eq("user_id", user["id"]).execute()
    return {"disconnected": True}


@router.get("/repos")
async def list_repos(
    user: dict = Depends(get_current_user),
):
    """List user's GitHub repositories."""
    gh = get_github_service(user["id"])
    if not gh:
        raise HTTPException(status_code=400, detail="GitHub not connected")
    return gh.list_repos()


@router.post("/repos")
async def create_repo(
    body: CreateRepoRequest,
    user: dict = Depends(get_current_user),
):
    """Create a new GitHub repository."""
    gh = get_github_service(user["id"])
    if not gh:
        raise HTTPException(status_code=400, detail="GitHub not connected")
    try:
        return gh.create_repo(body.name, body.description, body.private)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/push")
async def push_pipeline_code(
    body: PushCodeRequest,
    user: dict = Depends(get_current_user),
    supabase: Client = Depends(get_supabase_dependency),
):
    """Push pipeline artifacts (code, configs) to a GitHub repo."""
    gh = get_github_service(user["id"])
    if not gh:
        raise HTTPException(status_code=400, detail="GitHub not connected")

    _assert_pipeline_access(body.pipeline_id, user["id"], supabase)

    artifacts = (
        supabase.table("artifacts")
        .select("*")
        .eq("pipeline_id", body.pipeline_id)
        .order("created_at")
        .execute()
    )
    if not artifacts.data:
        raise HTTPException(status_code=404, detail="No artifacts found for this pipeline")

    files: dict[str, str] = {}
    for artifact in artifacts.data:
        content = artifact.get("content", {})
        stage = str(artifact.get("stage_name", "") or "stage")
        artifact_type = str(artifact.get("artifact_type", "") or "artifact")
        version = int(artifact.get("version", 1) or 1)

        extracted = _extract_files(content)
        if extracted:
            files.update(extracted)
            continue

        folder = "docs"
        if stage == "implementation":
            folder = "src"
        elif stage == "deployment":
            folder = "deploy"
        file_name = f"{folder}/{stage}_{artifact_type}_v{version}.json"
        files[file_name] = _to_json(content)

    if not files:
        raise HTTPException(status_code=400, detail="No pushable files found in artifacts")

    target_branch = body.branch
    if target_branch:
        try:
            gh.create_branch(body.repo_full_name, target_branch)
        except Exception:
            pass

    result = gh.push_files(
        repo_name=body.repo_full_name,
        files=files,
        commit_message=body.commit_message,
        branch=target_branch,
    )

    pr_info = None
    if body.create_pr and target_branch:
        try:
            pr_info = gh.create_pull_request(
                repo_name=body.repo_full_name,
                title=body.commit_message,
                body=(
                    "Auto-generated by Multi-Agent Pipeline\n\n"
                    f"Pipeline ID: {body.pipeline_id}\n\n"
                    f"Files: {len(files)}"
                ),
                head=target_branch,
            )
        except Exception as exc:
            pr_info = {"error": str(exc)}

    supabase.table("pipeline_events").insert({
        "pipeline_id": body.pipeline_id,
        "event_type": "code_pushed",
        "message": f"Code pushed to {body.repo_full_name}",
        "data": {
            "commit": result,
            "pull_request": pr_info,
        },
    }).execute()

    return {
        "commit": result,
        "pull_request": pr_info,
        "files_pushed": list(files.keys()),
    }


@router.post("/branches")
async def create_branch(
    body: CreateBranchRequest,
    user: dict = Depends(get_current_user),
):
    """Create a new branch on a repo."""
    gh = get_github_service(user["id"])
    if not gh:
        raise HTTPException(status_code=400, detail="GitHub not connected")
    try:
        return gh.create_branch(body.repo_full_name, body.branch_name, body.from_branch)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


def _to_json(data: Any) -> str:
    """Pretty-print arbitrary data to JSON string."""
    return json.dumps(data, indent=2, default=str)
