"""
GitHub integration service — manage repos, branches, and push code from pipeline artifacts.

Uses PyGithub (REST API) for repo management and code push operations.
"""

from __future__ import annotations

import base64
import logging
from typing import Optional
import httpx

from github import Github, GithubException, InputGitTreeElement
from backend.app.supabase_client import get_supabase
from backend.app.config import get_settings

logger = logging.getLogger(__name__)

GITHUB_OAUTH_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_API_URL = "https://api.github.com"
GITHUB_SCOPES = "repo,admin:repo_hook,read:org,user:email"


class GitHubService:
    """Manages GitHub operations for a user's connected account."""

    def __init__(self, access_token: str):
        self.gh = Github(access_token)
        self.user = self.gh.get_user()

    @property
    def username(self) -> str:
        return self.user.login

    @staticmethod
    def get_oauth_url(state: str) -> str:
        from urllib.parse import quote
        settings = get_settings()
        redirect_uri = f"{settings.backend_url.rstrip('/')}/api/github/oauth/callback"
        return (
            f"{GITHUB_OAUTH_URL}"
            f"?client_id={settings.github_client_id}"
            f"&scope={GITHUB_SCOPES}"
            f"&state={state}"
            f"&redirect_uri={quote(redirect_uri, safe='')}"
        )

    @staticmethod
    def exchange_code(code: str) -> dict:
        settings = get_settings()
        with httpx.Client(timeout=20.0) as client:
            response = client.post(
                GITHUB_TOKEN_URL,
                headers={"Accept": "application/json"},
                data={
                    "client_id": settings.github_client_id,
                    "client_secret": settings.github_client_secret,
                    "code": code,
                    "redirect_uri": f"{settings.backend_url.rstrip('/')}/api/github/oauth/callback",
                },
            )
            response.raise_for_status()
            return response.json()

    @staticmethod
    def get_user_info_from_token(access_token: str) -> dict:
        with httpx.Client(timeout=20.0) as client:
            user_response = client.get(
                f"{GITHUB_API_URL}/user",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/vnd.github+json",
                },
            )
            user_response.raise_for_status()
            user_data = user_response.json()

            if not user_data.get("email"):
                emails_response = client.get(
                    f"{GITHUB_API_URL}/user/emails",
                    headers={
                        "Authorization": f"Bearer {access_token}",
                        "Accept": "application/vnd.github+json",
                    },
                )
                emails_response.raise_for_status()
                emails = emails_response.json()
                primary = next((e for e in emails if e.get("primary") and e.get("verified")), None)
                if primary:
                    user_data["email"] = primary.get("email")

            return user_data

    def list_repos(self, limit: int = 30) -> list[dict]:
        """List user's repositories."""
        repos = self.user.get_repos(sort="updated")
        return [
            {
                "id": repo.id,
                "name": repo.name,
                "full_name": repo.full_name,
                "description": repo.description or "",
                "url": repo.html_url,
                "private": repo.private,
                "default_branch": repo.default_branch,
                "language": repo.language,
                "updated_at": repo.updated_at.isoformat() if repo.updated_at else None,
                "stars": repo.stargazers_count,
            }
            for repo in list(repos[:limit])
        ]

    def create_repo(
        self,
        name: str,
        description: str = "",
        private: bool = True,
        auto_init: bool = True,
    ) -> dict:
        """Create a new repository."""
        repo = self.user.create_repo(
            name=name,
            description=description,
            private=private,
            auto_init=auto_init,
        )
        return {
            "id": repo.id,
            "name": repo.name,
            "full_name": repo.full_name,
            "url": repo.html_url,
            "clone_url": repo.clone_url,
            "default_branch": repo.default_branch,
        }

    def push_files(
        self,
        repo_name: str,
        files: dict[str, str],
        commit_message: str = "feat: auto-generated by Multi-Agent Pipeline",
        branch: Optional[str] = None,
    ) -> dict:
        """
        Push multiple files to a GitHub repo in a single commit.

        Args:
            repo_name: Full repo name (e.g., "user/repo")
            files: Dict of {file_path: file_content}
            commit_message: Commit message
            branch: Target branch (defaults to repo's default branch)

        Returns:
            Dict with commit info
        """
        repo = self.gh.get_repo(repo_name)
        branch = branch or repo.default_branch

        # Get the latest commit SHA on the branch
        ref = repo.get_git_ref(f"heads/{branch}")
        latest_commit = repo.get_git_commit(ref.object.sha)
        base_tree = latest_commit.tree

        # Build tree elements for all files
        tree_elements = []
        for path, content in files.items():
            blob = repo.create_git_blob(content, "utf-8")
            tree_elements.append(
                InputGitTreeElement(
                    path=path,
                    mode="100644",
                    type="blob",
                    sha=blob.sha,
                )
            )

        # Create tree and commit
        new_tree = repo.create_git_tree(tree_elements, base_tree)
        new_commit = repo.create_git_commit(
            message=commit_message,
            tree=new_tree,
            parents=[latest_commit],
        )
        ref.edit(sha=new_commit.sha)

        return {
            "sha": new_commit.sha,
            "message": commit_message,
            "url": f"https://github.com/{repo_name}/commit/{new_commit.sha}",
            "files_pushed": len(files),
        }

    def create_branch(
        self,
        repo_name: str,
        branch_name: str,
        from_branch: Optional[str] = None,
    ) -> dict:
        """Create a new branch."""
        repo = self.gh.get_repo(repo_name)
        source = from_branch or repo.default_branch
        source_ref = repo.get_git_ref(f"heads/{source}")

        try:
            ref = repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=source_ref.object.sha,
            )
            return {
                "branch": branch_name,
                "sha": ref.object.sha,
                "source": source,
            }
        except GithubException as e:
            if e.status == 422:  # Branch already exists
                return {
                    "branch": branch_name,
                    "sha": source_ref.object.sha,
                    "source": source,
                    "already_exists": True,
                }
            raise

    def create_pull_request(
        self,
        repo_name: str,
        title: str,
        body: str,
        head: str,
        base: Optional[str] = None,
    ) -> dict:
        """Create a pull request."""
        repo = self.gh.get_repo(repo_name)
        base = base or repo.default_branch

        pr = repo.create_pull(
            title=title,
            body=body,
            head=head,
            base=base,
        )
        return {
            "number": pr.number,
            "url": pr.html_url,
            "title": pr.title,
            "state": pr.state,
        }


def get_github_token(user_id: str) -> Optional[str]:
    """Retrieve stored GitHub token for a user from Supabase."""
    supabase = get_supabase()
    result = (
        supabase.table("github_tokens")
        .select("access_token")
        .eq("user_id", user_id)
        .maybe_single()
        .execute()
    )
    if result.data:
        return result.data.get("access_token")
    return None


def get_github_service(user_id: str) -> Optional[GitHubService]:
    """Create a GitHubService for a user if they have a connected account."""
    token = get_github_token(user_id)
    if token:
        return GitHubService(token)
    return None
